
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    username: root
    password: 123456


logging:
  level:
    root: info
    com.smile: debug
  file: log/blog-dev.log

mybatis:
  configuration:
    call-setters-on-nulls: true #设置返回字段不为空，前端不报错
    map-underscore-to-camel-case: true #设置下划线转驼峰
  type-aliases-package: com.smile.po  #通过包设置映射类的别名


