spring:
  datasource:
    url: jdbc:mysql://cdb-6j6jktxk.bj.tencentcdb.com:10175/blog
    username: root
    password: '@bai880607'
logging:
  level:
    root: warn
    com.smile: info
  file: log/blog.log
server:
  port: 8081

mybatis:
  configuration:
    call-setters-on-nulls: true #设置返回字段不为空，前端不报错
    map-underscore-to-camel-case: true #设置下划线转驼峰
  type-aliases-package: com.smile.po  #通过包设置映射类的别名